### ISSUE TITLE
extract_features AssertionError

### ISSUE THREAD

**Issue by okmoments** [ddlBoJack/emotion2vec#44]
Traceback (most recent call last):
  File "/mnt/XXL/emotion2vec-large/scripts/extract_features.py", line 70, in <module>
    main()
  File "/mnt/XXL/emotion2vec-large/scripts/extract_features.py", line 39, in main
    model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([checkpoint_dir])
  File "/mnt/XXL/env/emotion2vec/lib/python3.9/site-packages/fairseq/checkpoint_utils.py", line 436, in load_model_ensemble_and_task
    task = tasks.setup_task(cfg.task)
  File "/mnt/XXL/env/emotion2vec/lib/python3.9/site-packages/fairseq/tasks/__init__.py", line 42, in setup_task
    assert (
AssertionError: Could not infer task type from {'_name': 'd2v_audio_classification', 'data': '/data/volume1/gaochangfeng.gcf/project/emo/fairseq_pai/examples/emo2vec/manifest/emo_box_fix', 'labels': 'lbl', ...

Is there any mismatch of code env?  fairseq=0.12.2, torch=1.13.1

**Comment by FANCY3210** [comment]
have you solved the assertionerror？
