### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'task'

### ISSUE THREAD

**Issue by tqzhou75** [ddlBoJack/emotion2vec#47]
I've tried many versions and encountered this issue every time. I would greatly appreciate it if you could provide a solution. Thank you very much.
Traceback (most recent call last):
  File "/home2/ZZT/emotion2vec-main/scripts/extract_features.py", line 76, in <module>
    main()
  File "/home2/ZZT/emotion2vec-main/scripts/extract_features.py", line 44, in main
    model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([checkpoint_dir])   #加载模型
  File "/home2/ZZT/anaconda3/envs/interspeech/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 279, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/home2/ZZT/anaconda3/envs/interspeech/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 232, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/home2/ZZT/anaconda3/envs/interspeech/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 420, in _upgrade_state_dict
    state["args"].task = "translation"
AttributeError: 'NoneType' object has no attribute 'task'

**Comment by FayJungkook** [comment]
I have also met this question

**Comment by tqzhou75** [comment]
@FayJungkook Hi, were you able to solve this issue?

**Comment by ddlBoJack** [comment]
Hi, the source code is only used for extracting features from the pretrained model. If you want to use the fine-tuned model, please use the FunASR pipeline.

**Comment by tqzhou75** [comment]
@ddlBoJack Thank you ever so much
