### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'task'

### ISSUE THREAD

**Issue by niuqingyu** [ddlBoJack/emotion2vec#52]
Traceback (most recent call last):
  File "extract_features.py", line 73, in <module>
    main()
  File "extract_features.py", line 42, in main
    model, cfg, task = fairseq.checkpoint_utils.load_model_ensemble_and_task([checkpoint_dir])
  File "/home/amax/miniconda3/envs/nqy_dev/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 279, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/home/amax/miniconda3/envs/nqy_dev/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 232, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/home/amax/miniconda3/envs/nqy_dev/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 420, in _upgrade_state_dict
    state["args"].task = "translation"
AttributeError: 'NoneType' object has no attribute 'task'

How can this task be solved?

**Comment by ddlBoJack** [comment]
Which checkpoint did you use? Please use FunASR pipeline for the fine-tuned checkpoint.

**Comment by niuqingyu** [comment]
Where did I get this from, did I see it in the Readme

---- Replied Message ----
| From | Ziyang ***@***.***> |
| Date | 11/10/2024 15:50 |
| To | ddlBoJack/emotion2vec ***@***.***> |
| Cc | niuqingyu ***@***.***>,
Author ***@***.***> |
| Subject | Re: [ddlBoJack/emotion2vec] AttributeError: 'NoneType' object has no attribute 'task' (Issue #52) |

Which checkpoint did you use? Please use FunASR pipeline for the fine-tuned checkpoint.

**Comment by ddlBoJack** [comment]
Which checkpoint did you want to use?

**Comment by niuqingyu** [comment]
FunASR pipeline for the fine-tuned checkpoint

**Comment by ddlBoJack** [comment]
There is no problem with FunASR pipeline.
